POST https://kalapaivakirja.herokuapp.com/api/entries
Content-Type: application/json

{
    "fish": "Ahven",
    "date": "2020-12-10",
    "length": "-",
    "weight": "-",
    "lure": "Hunter shad 3,5\" smelt",
    "place": "Palosaaren syv\u00e4nne",
    "coordinates": "-",
    "time": "20.0",
    "person": "Akseli"
}